### ISSUE TITLE
Project Page Stable Baselines

### ISSUE THREAD

**Issue by araffin** [DonsetPG/fenics-DRL#1]
Hello,

Interesting project =)

We would be glad if you could do a pull request on [stable-baselines](https://github.com/hill-a/stable-baselines) where you add your project to the [documentation](https://stable-baselines.readthedocs.io/en/master/misc/projects.html) (project section) ;)

**Comment by DonsetPG** [comment]
Hi, 

Thanks, I'll try to do it asap! 

Have a nice day
