### ISSUE TITLE
Negative drag values while training

### ISSUE THREAD

**Issue by troy1729** [DonsetPG/fenics-DRL#2]
Hi,

I've recently started using RL to fluid problems. So please excuse for naive questions. While training the value of drag force is coming negative using fenics. Then how come Cd graph is plotted with the positive value? Can you elaborate

Thanks

**Comment by DonsetPG** [comment]
Hi @troy1729,

Do you have an example of logs with negative drags and the associated Cd graph? 
Could you also let me know the versions you are using?

Thanks a lot

**Comment by alarcher** [comment]
Is it not related to formulating the maximization of the reward as minimization of the drag by flipping the sign?

**Comment by DonsetPG** [comment]
I thought about that but he is only mentioning the drag, not the reward... 
+ the code is not flipping the sign of the drag to compute the reward (but adding weird constants tho haha).
