### ISSUE TITLE
No matching distribution found for ale-py~=0.7.5; extra == "atari" (from gym[atari])

### ISSUE THREAD

**Issue by jiangzhangze** [DonsetPG/fenics-DRL#3]
Hi @DonsetPG 
Thank you for your sharing.I met some errors while using pip install stable-baselines,which was run in fenics dockers images.

` ERROR: Could not find a version that satisfies the requirement ale-py~=0.7.5; extra == "atari" (from gym[atari]) (from versions: 0.6.0.dev20200207)
ERROR: No matching distribution found for ale-py~=0.7.5; extra == "atari" (from gym[atari])`

**Comment by DonsetPG** [comment]
Hi @jiangzhangze,
Not sure what the issue is, maybe trying the latest installations method could help:
```
pip install gym[all]
```

and
```
sudo apt-get update && sudo apt-get install cmake libopenmpi-dev python3-dev zlib1g-dev
pip install stable-baselines[mpi]
```

**Comment by jiangzhangze** [comment]
Hi @DonsetPG 
Apologize for my late reply.`pip install gym[all]` seems don't work,could you tell me the version of required libraries.
